baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'limanshu'


#defaultContentLanguage = "zh"
#defaultContentLanguageInSubdir = true
#
#[languages]
#[languages.en]
#languageCode = "en-US"
#languageName = "English"
#weight = 1
#
#[languages.zh]
#languageCode = "zh-CN"
#languageName = "中文"
#weight = 2



[permalinks]
pages = "/:slug"

[params]
logo = '/assets/favicon.png'
description = "A hugo"
author = 'author'
items = 5

[params.comments]
enabled = false
githubRepo = 'xx/xx'
theme = 'github-light'


[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = "-110"
[[menu.main]]
identifier = "posts"
name = "Post"
url = "/posts/"
weight = -200

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokailight'
tabWidth = 4

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[outputFormats.JSON]
mediatype = "application/json"
baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
